### ISSUE TITLE
Ajouter thème particulier pour le root

### ISSUE THREAD

**Issue by Oodnadatta** [REGOVAR/ServerConfiguration#3]
exemple : ZSH_THEME="nebirhos

**Comment by Arkanosis** [comment]
> ajouter thème particulier pour le root exemple : ZSH_THEME="nebirhos"

Better to leave the root user with the dumb default bash IMHO. Maybe with a red prompt or whatever, but the idea is that the root account isn't used interactively (one should use sudo instead) so “comfort” is actually an anti-feature. Plus, both zsh and custom themes come with their own security implications one wants to avoid on a production server (eg. [this theme](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/nebirhos.zsh-theme) alone execs `rvm-prompt`, `rbenv`… — not counting what oh-my-zsh could do).

Just my 2 cts.
