### ISSUE TITLE
Upgrade to Debian Stretch before creating the regovarpg user in PostgreSQL

### ISSUE THREAD

**Issue by Arkanosis** [REGOVAR/ServerConfiguration#9]
The version of SaltStack shipped with Debian Jessie cannot do it on versions of PostgreSQL ≥ ~~5.5~~ 9.5, and we install PostgreSQL ~~5.6~~ 9.6 from jessie-backports.

See saltstack/salt#26845 for more information.

**Comment by ikit** [comment]
We install PostgreSQL 5.6 ?
Regovar is using 9.6...

I guess I missed something :)

**Comment by Arkanosis** [comment]
Not enough sleep, obviously. I've fixed the above issue. Thanks!
